### ISSUE TITLE
Laravel v5.6.*

### ISSUE THREAD

**Issue by ghost** [z-song/redis-manager#11]
Problem 1
    - Installation request for encore/redis-manager ^0.1.1 -> satisfiable by encore/redis-manager[v0.1.1].
    - Conclusion: remove laravel/framework v5.6.12
    - Conclusion: don't install laravel/framework v5.6.12
    - encore/redis-manager v0.1.1 requires illuminate/contracts 5.5.* -> satisfiable by illuminate/contracts[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - don't install illuminate/contracts v5.5.0|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.16|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.17|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.2|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.28|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.33|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.34|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.35|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.36|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.37|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.39|don't install laravel/framework v5.6.12
    - don't install illuminate/contracts v5.5.40|don't install laravel/framework v5.6.12
    - Installation request for laravel/framework (locked at v5.6.12, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.12].

**Comment by z-song** [comment]
Fixed, please try again
